### ISSUE TITLE
World block recycling

### ISSUE THREAD

**Issue by mrozbarry** [coconut-platformer/game#10]
## Tasks

 - [x] Only render the number of blocks to show on the screen
 - [x] When a block goes off screen, destroy it
 - [x] When a block goes off screen, create a new one.
