### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by mrozbarry** [coconut-platformer/game#32]
## Tasks

 - [x] World-based movement
 - [x] Camera follows coconut
 - [ ] Camera x offsets based on amount of "juice"
